### ISSUE TITLE
Семестр 4, Лаба 1

### ISSUE THREAD

**Issue by KyouKiSu** [K0TlK/NSTU-Labs#1]
Действительно ли надо было наследовать абстрактным классом ant суперкласс JComponent? Офк это работает, но выглядит стремно т.к. отрисовкой должен заниматься отрисовщик, а не сущность. Было ли это взято у Чарушина?)

Система спавна не очень, если произойдет залаг компа, намотается время - сущности не заспавнятся, хотя в теории могли бы. Да и "костыль" с остатком от деления не очень выглядит.

Screen.java, переменная wigth топ.

<3 с любовью от однокурсника

P.S. Я в курсе, что всем глубоко пофиг. Чисто чекаю систему Issues на гитхабе.
P.P.S. Сейчас позовут кого-то умного по Java и разнесут меня по фактам(

**Comment by KyouKiSu** [comment]
![image](https://user-images.githubusercontent.com/47526721/109983722-25af5e80-7d14-11eb-9514-ae94b725986b.png)

**Comment by K0TlK** [comment]
> Действительно ли надо было наследовать абстрактным классом ant суперкласс JComponent? Офк это работает, но выглядит стремно т.к. отрисовкой должен заниматься отрисовщик, а не сущность. Было ли это взято у Чарушина?)
> 
> Система спавна не очень, если произойдет залаг компа, намотается время - сущности не заспавнятся, хотя в теории могли бы. Да и "костыль" с остатком от деления не очень выглядит.
> 
> Screen.java, переменная wigth топ.
> 
> <3 с любовью от однокурсника
> 
> P.S. Я в курсе, что всем глубоко пофиг. Чисто чекаю систему Issues на гитхабе.
> P.P.S. Сейчас позовут кого-то умного по Java и разнесут меня по фактам(
